-- Create / replace event_family_map (medium mapping)
CREATE OR REPLACE TABLE `innova-gewoon.reporting.Flat_events_map table`  AS
SELECT * FROM UNNEST([
  STRUCT('first_visit' AS event_name,'acquisition' AS family),
  STRUCT('session_start','acquisition'),
  STRUCT('user_engagement','acquisition'),
  STRUCT('page_view','browse'),
  STRUCT('scroll','browse'),
  STRUCT('view_search_results','browse'),
  STRUCT('product','browse'),
  STRUCT('productconfiguration','browse'),
  STRUCT('click_google_play','browse'),
  STRUCT('click_app_store','browse'),
  STRUCT('click','browse'),
  STRUCT('inloggen_click_homepage','browse'),
  STRUCT('form_start','form'),
  STRUCT('form_submit','form'),
  STRUCT('postcode_ingevuld','form'),
  STRUCT('persoonlijk_aanod_ingevuld_page3','form'),
  STRUCT('address','form'),
  STRUCT('telefoonnummer_error','form_error'),
  STRUCT('rekeningnummer_error','form_error'),
  STRUCT('geboortedatum_error','form_error'),
  STRUCT('email_bevestiging_error','form_error'),
  STRUCT('voorletters_error','form_error'),
  STRUCT('voornaam_error','form_error'),
  STRUCT('achternaam_error','form_error'),
  STRUCT('email_error','form_error'),
  STRUCT('begin_checkout','checkout'),
  STRUCT('marketsegment','checkout'),
  STRUCT('flex_switch_checked','checkout'),
  STRUCT('relation','checkout'),
  STRUCT('purchase','purchase'),
  STRUCT('bedankpagina_retentie','post_purchase'),
  STRUCT('retentie_bestelling','post_purchase'),
  STRUCT('usage','usage'),
  STRUCT('file_download','files'),
  STRUCT('undefined','other'),
  STRUCT('doorstroomproces_contract','other')
]);
